apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-script
  namespace: mongodb
data:
  auto-join.sh: |
    #!/bin/bash
    set -e

    HOSTNAME=$(hostname)
    REPLICA_SET="rs0"
    PRIMARY_HOST="mongodb-0.mongodb.mongodb.svc.cluster.local:27017"
    POD_NAME=$(hostname -s)

    echo "Starting MongoDB Auto Join script"
    echo "Pod Name: $POD_NAME"

    if [[ "$POD_NAME" == "mongodb-0" ]]; then
      echo "Initiating Replica Set on $POD_NAME..."
      mongod --replSet "$REPLICA_SET"
      mongo --eval "rs.initiate({_id: '$REPLICA_SET', members: [{_id: 0, host: '$POD_NAME.mongodb.mongodb.svc.cluster.local:27017' }]})"
    else
       echo "Joining existing replica set..."
        until mongo --host "$PRIMARY_HOST" --eval "printjson(rs.isMaster())" | grep '"ismaster" : true'; do
          echo "Waiting for primary to be ready..."
          sleep 5
        done        
        mongo --host "$PRIMARY_HOST" --eval "rs.add('$POD_NAME.mongodb.mongodb.svc.cluster.local:27017')"
    fi

    echo "MongoDB Auto Join script completed"

    if [[ "$1" ]]; then
      echo "Executing provided command: $*"
      exec "$@"
    else
      echo "No command provided. Exiting."
      exit 0
    fi
