apiVersion: v1
kind: Service
metadata:
  name: ecommerce-nodejs
  labels:
    app: ecommerce-nodejs
spec:
  selector:
    app: ecommerce-nodejs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
